### ISSUE TITLE
Left Justify "Search" and "Collection Organization"

### ISSUE THREAD

**Issue by dlavoie2nd** [NEU-Libraries/archivesspace_plugin#10]
Left justify "Search" and "Collection Organization" on the collection finding aid page.
![aspace collection search_tree](https://user-images.githubusercontent.com/35612680/42645593-733fabc4-85cc-11e8-937b-46385f5d09b5.png)

**Comment by gam5** [comment]
This is in place on the dev site. http://liblab.northeastern.edu:8081/  -- Not sure how I feel about it. Let me know what you think.

Greg

**Comment by dlavoie2nd** [comment]
The concept behind issue #8 was to mirror the design of Scholar OneSearch.

![screen shot 2018-09-13 at 2 08 59 pm](https://user-images.githubusercontent.com/35612680/45507454-2dec3b80-b760-11e8-9d38-0d4459060387.png)

Is it possible to left justify the collection records?

![screen shot 2018-09-13 at 2 06 08 pm](https://user-images.githubusercontent.com/35612680/45507469-393f6700-b760-11e8-8784-5fe50eed1757.png)

**Comment by gam5** [comment]
Oops, an unexpected consequence of an unrelated CSS change. Has been fixed.

Greg

**Comment by gam5** [comment]
It was decided to keep "Search" and "Collection Organization" on the right for now. Changes to core code needed to move to the right without breaking a ton of other stuff.
