### ISSUE TITLE
Wireframe

### ISSUE THREAD

**Issue by dlavoie2nd** [NEU-Libraries/archivesspace_plugin#11]
https://wireframe.cc/pro/pp/7a391f306176481

We are basing our homepage design on Brandeis - http://findingaids.brandeis.edu.  This rounds out our current requests.

**Comment by gam5** [comment]
Do you have thoughts on the images you want to use? I'm using ones from Brandeis right now. 

It's still a work in progress, but you can follow along here: http://liblab.northeastern.edu:8081/

**Comment by nestochan** [comment]
Links in wireframe un-clickable or copy/paste-able here they are extracted from dev inspect mode

* Freedom House Coalition Press Conference; link to image here: http://hdl.handle.net/2047/d20155744
* Tunnel Geometry photo; link to photo here: http://hdl.handle.net/2047/D20254341
* Boston Phoenix promo image: https://news.northeastern.edu/wp-content/uploads/2015/11/BostonPhoenix1-740x493.jpg

**Comment by dlavoie2nd** [comment]
"Search the Archives" - For the landing page search bar we wanted to keep "keyword" and "years" filters but remove "Search all/limit to" drop down menu.

**Comment by dlavoie2nd** [comment]
On all pages except the landing page we wanted to add an icon guide.

![screen shot 2018-09-14 at 12 13 47 pm](https://user-images.githubusercontent.com/35612680/45562646-f7262c00-b818-11e8-8b4d-76cbe9a03abc.png)
