### ISSUE TITLE
Search Results Final Comments

### ISSUE THREAD

**Issue by dlavoie2nd** [NEU-Libraries/archivesspace_plugin#14]
Please remove "Subjects" and "Names" from toolbar.
Please remove "Repository" from "Additional filters".
Please change "Collections", "Unprocessed", "Series", and "File" icon colors to #69656f.

![search results](https://user-images.githubusercontent.com/35612680/45839574-b596f480-bce2-11e8-842f-30caafc2af3f.png)

**Comment by gam5** [comment]
Subjects and Names disabled in config.rb

**Comment by gam5** [comment]
Colors updated.

**Comment by gam5** [comment]
I haven't found a way to remove "Repository" from "Additional filters" without messing other things up. I'll leave this issue open for now.

**Comment by gam5** [comment]
For future reference. https://groups.google.com/forum/#!topic/archivesspace/aTVwL_fm-gE

**Comment by nestochan** [comment]
is this still pending @gam5

**Comment by gam5** [comment]
Yes. I'll revisit the problem now and update the ticket when I have more info.

**Comment by nestochan** [comment]
🍻

**Comment by gam5** [comment]
"Repository" has been removed from "Additional filters" on the test server. The new functionality will be available in production after the next restart.
