### ISSUE TITLE
Left Justify "Filter Results"

### ISSUE THREAD

**Issue by dlavoie2nd** [NEU-Libraries/archivesspace_plugin#8]
Left justify "Filter Results" on "Collections", "Unprocessed Materials", "Subjects", "Names", and "Record Groups" pages.

"Collections"
![aspacecollections filter](https://user-images.githubusercontent.com/35612680/42644843-90087404-85ca-11e8-864d-4826d48626de.png)
"Unprocessed Materials"
![aspace unprocesssed filter](https://user-images.githubusercontent.com/35612680/42644854-986a19ae-85ca-11e8-9b61-78ed943c4cf7.png)
"Subjects"
![aspace subjects filter](https://user-images.githubusercontent.com/35612680/42644863-a2745b1c-85ca-11e8-8e5e-5ed24d58555d.png)
"Names"
![aspace names filter](https://user-images.githubusercontent.com/35612680/42644870-a7e2b3aa-85ca-11e8-9115-8d347e2b42b3.png)
"Record Groups"
![aspace record groups filter](https://user-images.githubusercontent.com/35612680/42644890-b204c602-85ca-11e8-87a9-1141ec1ab599.png)

**Comment by gam5** [comment]
This is in place on the dev site. http://liblab.northeastern.edu:8081/ -- Not sure how I feel about it. Let me know what you think.

Greg

**Comment by dlavoie2nd** [comment]
The concept behind issue #8 was to mirror the design of Scholar OneSearch.

[cid:5DD2A9D7-EC9C-49C2-97F1-8F66530DCEB2]

Is it possible to left justify the collection records?

[cid:910D3EA4-7EE1-4466-A7E1-2C08037AA18D]

Daniel J. Lavoie II
Collections Archivist
Northeastern University Libraries
Archives and Special Collections
92 Snell Library
360 Huntington Avenue
Boston, MA 02115

617.373.3317
d.lavoie@northeastern.edu
